version: '3.1'

services:
    db:
        image: mysql:5.7
        depends_on:
        - redis
        ports:
          - "3306:3306"
        environment:
          MYSQL_USER: main
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DB: main
        

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
          - PMA_ARBITRARY=1
        restart: always
        ports:
         - 8899:80
        

    redis:
        image: redis
        ports: 
        - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: 
        - "5672:15672"

    