version: '3.1'

services:
    database:
        image: mysql:5.7
        depends_on:
        - redis
        ports: [3306]

        environment:
          POSTGRES_USER: main
          POSTGRES_PASSWORD: main
          POSTGRES_DB: main
       

    redis:
        image: redis
        ports: 
        - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.7-management
        ports: 
        - "5672:15672"

    