easy_admin:
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        menu:
            - { entity: 'Famille', label: 'Familles' }
            - { entity: 'Animal', label: 'Animaux' }
            - { entity: 'User', label: 'Utilisateurs' }
            - { entity: 'Membre', label: 'Membres' }
    formats:
        datetime: 'd/m/Y à H:i'
