easy_admin:
    entities:
        Membre:
            class: App\Entity\Membre
            list:
                fields:
                    - nom
                    - prenom
                    - telephone